// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using System.Drawing;

namespace MyIdOnMac
{
	public partial class EditController : NSViewController
	{
        public IdItem AIdItem = null;

        private NSViewController _presentor;
		public NSViewController Presentor
		{
			get { return _presentor; }
			set { _presentor = value; }
		}

        

        public EditController (IntPtr handle) : base (handle)
		{
            //uxHint.Text = "";
            if (AIdItem != null)
            {
                uxSite.StringValue = AIdItem.Site;
                uxUser.StringValue = AIdItem.User;
                uxPassword.StringValue = AIdItem.Password;
                uxMemo.StringValue = AIdItem.Memo;
                //uxHint.Text = AIdItem.PasswordTip;
                //if (uxHint.Text != "")
                    //uxHint.ForeColor = Color.Red;
            }
            else
                AIdItem = new IdItem();
        }

		private void CloseDialog()
		{
			Presentor.DismissViewController(this);
		}

        partial void OkDialog(NSObject sender)
        {
            AIdItem.Site = uxSite.StringValue;
            AIdItem.User = uxUser.StringValue;
            AIdItem.Password = uxPassword.StringValue;
            AIdItem.Memo = uxMemo.StringValue;

            RaiseDialogAccepted();
			CloseDialog();
        }

        partial void CancelDialog(NSObject sender)
        {
			RaiseDialogCancelled();
			CloseDialog();
        }

		public EventHandler DialogAccepted;
		internal void RaiseDialogAccepted()
		{
			if (this.DialogAccepted != null)
			{
				this.DialogAccepted(this, EventArgs.Empty);
			}
		}

		public EventHandler DialogCanceled;
		internal void RaiseDialogCancelled()
		{
			if (this.DialogCanceled != null)
				this.DialogCanceled(this, EventArgs.Empty);
		}
    }
}
