// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace MyIdOnMac
{
	public partial class OpenDataFileViewController : NSViewController
	{
        public NSViewController Presentor;

        public string DataFile { get { return this.uxDataFile.StringValue; } }

        public bool PrivateKeyOnDisk { get { return uxPriviateKeyOn.State == NSCellStateValue.On; } }

        public string PrivateKeyFile { get { return uxPrivateKeyFile.StringValue; } }

        public OpenDataFileViewController (IntPtr handle) : base (handle)
		{
		}

        private void CloseDialog()
        {
            Presentor.DismissViewController(this);
        }

        partial void okDialog(NSObject sender)
        {
            if (uxPriviateKeyOn.State == NSCellStateValue.On)
            {
                if (!System.IO.File.Exists(uxPrivateKeyFile.StringValue))
                {
                    var alert = new NSAlert()
                    {
                        AlertStyle = NSAlertStyle.Warning,
                        InformativeText = $"File not found: {uxPrivateKeyFile.StringValue}",
                        MessageText = "Unable to open private key file",
                    };
                    alert.BeginSheet(this.View.Window);
                    return;
  
                }
            }
            if (!System.IO.File.Exists(uxDataFile.StringValue))
            {
                var alert = new NSAlert()
                {
                    AlertStyle = NSAlertStyle.Warning,
                    InformativeText = $"File not found: {uxDataFile.StringValue}",
                    MessageText = "Data file not found",
                };
                alert.BeginSheet(this.View.Window);
                return;
            }
            
                       
            RaiseDialogOk();
            CloseDialog();
        }



        public EventHandler DialogOk;
        internal void RaiseDialogOk()
        {
            if (this.DialogOk != null)
            {
                this.DialogOk(this, EventArgs.Empty);
            }
        }

        partial void cancelDialog(NSObject sender)
        {
            RaiseDialogCancelled();
            CloseDialog();
        }

       

        public EventHandler DialogCanceled;
        internal void RaiseDialogCancelled()
        {
            if (this.DialogCanceled != null)
                this.DialogCanceled(this, EventArgs.Empty);
        }


        partial void browseDataFile(NSObject sender)
        {
            var panel = new NSOpenPanel();

            panel.ReleasedWhenClosed = true;

            string p = uxDataFile.StringValue;
            if (string.IsNullOrWhiteSpace(p))
                p = System.IO.Path.Combine(KnownFolders.DataDir, "myid_secret.data");

            panel.NameFieldStringValue = System.IO.Path.GetFileName(p);
            panel.Directory = System.IO.Path.GetDirectoryName(p);

            panel.AllowedFileTypes = new string[] { "data" };

            panel.BeginSheet(this.View.Window, ret =>
            {
                if (ret == 1 && !string.IsNullOrWhiteSpace(panel.Filename))
                {
                    uxDataFile.StringValue = panel.Filename;

                }
            });


        }

        partial void browsePrivateKey(NSObject sender)
        {
            var panel = new NSOpenPanel();

            panel.ReleasedWhenClosed = true;

            string p = uxPrivateKeyFile.StringValue;
            if (string.IsNullOrWhiteSpace(p))
                p = System.IO.Path.Combine(KnownFolders.DataDir, "private.key");

            panel.NameFieldStringValue = System.IO.Path.GetFileName(p);
            panel.Directory = System.IO.Path.GetDirectoryName(p);

            panel.AllowedFileTypes = new string[] { "key" };

            panel.BeginSheet(this.View.Window, ret =>
            {
                if (ret == 1 && !string.IsNullOrWhiteSpace(panel.Filename))
                {
                    uxPrivateKeyFile.StringValue = panel.Filename;

                }
            });


        }

        partial void privateKeySelectionChanged(Foundation.NSObject sender)
        {
            var check = sender as NSButton;

            uxPrivateKeyFile.Enabled = (check.Tag == 2);
            uxBrowsePrivateKeyFile.Enabled = (check.Tag == 2);

        }
    }
}
