// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace MyIdOnMac
{
	public partial class SignInViewController : NSViewController
	{
		public SignInViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
