// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using System.Text;

namespace MyIdOnMac
{
	public partial class SignInViewController : NSViewController
	{
     
        public NSViewController Presentor;

        public string Password { get { return uxPassword.StringValue; } }


        public SignInViewController (IntPtr handle) : base (handle)
		{
		}

        partial void OkDialog(NSObject sender)
        {
            //byte[] pin = UxListDataSource.GetKeyIv("Pin");

            //string savedPin = Encoding.Unicode.GetString(pin);
            //if (savedPin == uxPassword.StringValue)
            //{
                RaiseDialogAccepted();
                CloseDialog();
            //}
            //else
            //{
            //    var alert = new NSAlert()
            //    {
            //        AlertStyle = NSAlertStyle.Warning,
            //        InformativeText = "Please enter the correct Master PIN and try again",
            //        MessageText = "Incorrect Master PIN",
            //    };
            //    alert.BeginSheet(this.View.Window);
            //}
        }

        private void CloseDialog()
        {
            Presentor.DismissViewController(this);
        }
        partial void CancelDialog(NSObject sender)
        {
            RaiseDialogCancelled();
            CloseDialog();
        }

        public EventHandler DialogAccepted;
        internal void RaiseDialogAccepted()
        {
            if (this.DialogAccepted != null)
            {
                this.DialogAccepted(this, EventArgs.Empty);
            }
        }

        public EventHandler DialogCanceled;
        internal void RaiseDialogCancelled()
        {
            if (this.DialogCanceled != null)
                this.DialogCanceled(this, EventArgs.Empty);
        }
    }
}
