// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace MyIdOnMac
{
	public partial class WelcomeController : NSViewController
	{
        public string DataFile { get { return this.uxDataFile.StringValue; } }

        public string MasterPin { get { return this.uxMasterPin.StringValue; } }

        public WelcomeController (IntPtr handle) : base (handle)
		{
            
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            string file = System.IO.Path.Combine(KnownFolders.DataDir, "myid_secret.data");
            uxDataFile.StringValue = file;
        }

        private NSViewController _presentor;
        public NSViewController Presentor
        {
            get { return _presentor; }
            set { _presentor = value; }
        }

        private void CloseDialog()
        {
            Presentor.DismissViewController(this);
        }

        partial void OkDialog(NSObject sender)
        {
            if (System.IO.File.Exists(uxDataFile.StringValue))
            {
                var alert = new NSAlert()
                {
                    AlertStyle = NSAlertStyle.Warning,
                    InformativeText = $"Data file already exists: {uxDataFile.StringValue}",
                    MessageText = "Create new data file",
                };
                alert.RunModal();
                return;
            }
            RaiseDialogOk();
            CloseDialog();
        }

        

        public EventHandler DialogOk;
        internal void RaiseDialogOk()
        {
            if (this.DialogOk != null)
            {
                this.DialogOk(this, EventArgs.Empty);
            }
        }

        partial void CancelDialog(NSObject sender)
        {
            RaiseDialogCancelled();
            CloseDialog();
        }
        public EventHandler DialogCanceled;
        internal void RaiseDialogCancelled()
        {
            if (this.DialogCanceled != null)
                this.DialogCanceled(this, EventArgs.Empty);
        }

        partial void OpenDialog(NSObject sender)
        {
            RaiseDialogOpen();
            CloseDialog();
        }
        public EventHandler DialogOpen;
        internal void RaiseDialogOpen()
        {
            if (this.DialogOpen != null)
                this.DialogOpen(this, EventArgs.Empty);
        }
    }
}
